### ISSUE TITLE
Penetration test finding - Too much information made public when errors are encountered

### ISSUE THREAD

**Issue by ctiijima** [open-horizon/exchange-api#194]
The following is from the penetration test team:

**Description**
Improper handling of errors can introduce a variety of security problems for a web site. The most common problem is when detailed internal error messages such as stack traces, database dumps, and error codes are displayed to the user (hacker). These messages reveal implementation details that should never be revealed. Such details can provide hackers important clues on potential flaws in the site and such messages are also disturbing to normal users.

**Affected URL/API(s)**
https://<host>:8443/ec-exchange/v1

**Request/Response**
Request:
POST /ec-exchange/v1/admin/hashpw?kra5c1=1 HTTP/1.1
Content-Type: application/json
Authorization: Basic cm9vdC9yb290OkpISmk4ZlkzQ1RUcGh4MlluQjNLUW0zZWFERDJibw== User-Agent: PostmanRuntime/7.15.0
Accept: */*
Cache-Control: no-cache
Postman-Token: e629747c-2ff0-4785-a09d-4d8252989ced
Host: <host>:8443
Accept-Encoding: gzip, deflate
Content-Length: 4
Connection: close
null

Response:
HTTP/1.1 500 Server Error
Date: Fri, 26 Jul 2019 09:52:16 GMT
Content-Type: text/plain;charset=utf-8
Content-Length: 7118
Connection: close
Access-Control-Allow-Credentials: true
Access-Control-Max-Age: 1800
Access-Control-Allow-Methods: GET,POST,PUT,DELETE,HEAD,OPTIONS,PATCH
java.lang.NullPointerException
at com.horizon.exchangeapi.AdminRoutes.$anonfun$$init$$2(AdminRoutes.scala:96) at org.scalatra.ScalatraBase.liftAction(ScalatraBase.scala:280)
at org.scalatra.ScalatraBase.$anonfun$invoke$1(ScalatraBase.scala:274)
at org.scalatra.ApiFormats.withRouteMultiParams(ApiFormats.scala:183)
at org.scalatra.ApiFormats.withRouteMultiParams$(ApiFormats.scala:169)
at com.horizon.exchangeapi.ExchangeApiApp.withRouteMultiParams(ExchangeApiApp.scala:24) at org.scalatra.ScalatraBase.invoke(ScalatraBase.scala:273)
at org.scalatra.ScalatraBase.invoke$(ScalatraBase.scala:272)
at
com.horizon.exchangeapi.ExchangeApiApp.org$scalatra$json$JsonSupport$$super$invoke(Exchange ApiApp.scala:24)
at org.scalatra.json.JsonSupport.$anonfun$invoke$1(JsonSupport.scala:90)
at org.scalatra.ApiFormats.withRouteMultiParams(ApiFormats.scala:183)
at org.scalatra.ApiFormats.withRouteMultiParams$(ApiFormats.scala:169)
at com.horizon.exchangeapi.ExchangeApiApp.withRouteMultiParams(ExchangeApiApp.scala:24) at org.scalatra.json.JsonSupport.invoke(JsonSupport.scala:84)
at org.scalatra.json.JsonSupport.invoke$(JsonSupport.scala:83)
at com.horizon.exchangeapi.ExchangeApiApp.invoke(ExchangeApiApp.scala:24)
at org.scalatra.ScalatraBase.$anonfun$runRoutes$3(ScalatraBase.scala:248)
at scala.Option.flatMap(Option.scala:171)
at org.scalatra.ScalatraBase.$anonfun$runRoutes$1(ScalatraBase.scala:246)
at scala.collection.immutable.Stream.flatMap(Stream.scala:489)
at org.scalatra.ScalatraBase.runRoutes(ScalatraBase.scala:245)
at org.scalatra.ScalatraBase.runRoutes$(ScalatraBase.scala:243)
at com.horizon.exchangeapi.ExchangeApiApp.runRoutes(ExchangeApiApp.scala:24)
at org.scalatra.ScalatraBase.runActions$1(ScalatraBase.scala:169)
at org.scalatra.ScalatraBase.$anonfun$executeRoutes$6(ScalatraBase.scala:181)
at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
at org.scalatra.ScalatraBase.cradleHalt(ScalatraBase.scala:199)
at org.scalatra.ScalatraBase.executeRoutes(ScalatraBase.scala:181)
at org.scalatra.ScalatraBase.executeRoutes$(ScalatraBase.scala:150)
at com.horizon.exchangeapi.ExchangeApiApp.executeRoutes(ExchangeApiApp.scala:24)
at org.scalatra.ScalatraBase.$anonfun$handle$1(ScalatraBase.scala:123)
at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58).......................

**Risk Assessment**
Sensitive information disclosed to public like server technology, class name, path, etc. can leverage remote attacks to application.

**Fix Recommendation**
Respond with generic error .

**Comment by bmpotter** [comment]
This is already fixed in exchange 2.7.2
