### ISSUE TITLE
Docker Exchange-api run error

### ISSUE THREAD

**Issue by Nitu-coder** [open-horizon/exchange-api#336]
My echange api build is successfull
but when i try to run the docker image using docker run image_name:tag
I get the following error after it starts running and then stops

2020-04-01 13:10:38,122 [ExchangeExecutor-1] INFO  c.m.v.c.i.AbstractPoolBackedDataSource - Initializing c3p0 pool... com.mchange.v2.c3p0.ComboPooledDataSource [ acquireIncrement -> 1, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, contextClassLoaderSource -> caller, dataSourceName -> 1bqq1hfa9ey1j151oiv08|31e75d13, debugUnreturnedConnectionStackTraces -> false, description -> null, driverClass -> org.postgresql.Driver, extensions -> {}, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, forceSynchronousCheckins -> false, forceUseNamedDriverClass -> false, identityToken -> 1bqq1hfa9ey1j151oiv08|31e75d13, idleConnectionTestPeriod -> 0, initialPoolSize -> 3, jdbcUrl -> , maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 0, maxIdleTimeExcessConnections -> 0, maxPoolSize -> 50, maxStatements -> 0, maxStatementsPerConnection -> 0, minPoolSize -> 1, numHelperThreads -> 3, preferredTestQuery -> null, privilegeSpawnedThreads -> false, properties -> {user=******, password=******}, propertyCycle -> 0, statementCacheNumDeferredCloseThreads -> 0, testConnectionOnCheckin -> false, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, userOverrides -> {}, usesTraditionalReflectiveProxies -> false ]
2020-04-01 13:11:08,224 [C3P0PooledConnectionPoolManager[identityToken->1bqq1hfa9ey1j151oiv08|31e75d13]-HelperThread-#0] WARN  c.m.v.resourcepool.BasicResourcePool - com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask@793a74da -- Acquisition Attempt Failed!!! Clearing pending acquires. While trying to acquire a needed new resource, we failed to succeed more than the maximum number of allowed acquisition attempts (30). Last acquisition attempt exception: 
java.sql.SQLException: No suitable driver
	at java.sql.DriverManager.getDriver(DriverManager.java:315)
	at com.mchange.v2.c3p0.DriverManagerDataSource.driver(DriverManagerDataSource.java:285)
	at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:175)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:203)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1176)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1163)
	at com.mchange.v2.resourcepool.BasicResourcePool.access$700(BasicResourcePool.java:44)
	at com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1908)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)
2020-04-01 13:11:08,224 [C3P0PooledConnectionPoolManager[identityToken->1bqq1hfa9ey1j151oiv08|31e75d13]-HelperThread-#2] WARN  c.m.v.resourcepool.BasicResourcePool - com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask@184392bf -- Acquisition Attempt Failed!!! Clearing pending acquires. While trying to acquire a needed new resource, we failed to succeed more than the maximum number of allowed acquisition attempts (30). Last acquisition attempt exception: 
java.sql.SQLException: No suitable driver
	at java.sql.DriverManager.getDriver(DriverManager.java:315)
	at com.mchange.v2.c3p0.DriverManagerDataSource.driver(DriverManagerDataSource.java:285)
	at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:175)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:203)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1176)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1163)
	at com.mchange.v2.resourcepool.BasicResourcePool.access$700(BasicResourcePool.java:44)
	at com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1908)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)
2020-04-01 13:11:08,225 [C3P0PooledConnectionPoolManager[identityToken->1bqq1hfa9ey1j151oiv08|31e75d13]-HelperThread-#0] WARN  c.m.v.resourcepool.BasicResourcePool - Having failed to acquire a resource, com.mchange.v2.resourcepool.BasicResourcePool@5e10e82c is interrupting all Threads waiting on a resource to check out. Will try again in response to new client requests.
2020-04-01 13:11:08,227 [C3P0PooledConnectionPoolManager[identityToken->1bqq1hfa9ey1j151oiv08|31e75d13]-HelperThread-#2] WARN  c.m.v.resourcepool.BasicResourcePool - Having failed to acquire a resource, com.mchange.v2.resourcepool.BasicResourcePool@5e10e82c is interrupting all Threads waiting on a resource to check out. Will try again in response to new client requests.
[ERROR] [04/01/2020 13:11:08.259] [main] [ExchApi(akka://actors)] Error: while upgrading the DB, the DB threw exception: Connections could not be acquired from the underlying database!
Exception in thread "main" java.lang.IllegalStateException: cannot create children while terminating or terminated
	at akka.actor.dungeon.Children.makeChild(Children.scala:287)
	at akka.actor.dungeon.Children.attachChild(Children.scala:49)
	at akka.actor.dungeon.Children.attachChild$(Children.scala:48)
	at akka.actor.ActorCell.attachChild(ActorCell.scala:447)
	at akka.actor.ActorSystemImpl.actorOf(ActorSystem.scala:783)
	at com.horizon.exchangeapi.ExchangeApiApp$.delayedEndpoint$com$horizon$exchangeapi$ExchangeApiApp$1(ExchangeApiApp.scala:250)
	at com.horizon.exchangeapi.ExchangeApiApp$delayedInit$body.apply(ExchangeApiApp.scala:59)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1$adapted(App.scala:80)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.App.main(App.scala:80)
	at scala.App.main$(App.scala:78)
	at com.horizon.exchangeapi.ExchangeApiApp$.main(ExchangeApiApp.scala:59)
	at com.horizon.exchangeapi.ExchangeApiApp.main(ExchangeApiApp.scala)
2020-04-01 13:11:08,303 [ExchangeExecutor-2] WARN  c.m.v.resourcepool.BasicResourcePool - com.mchange.v2.resourcepool.BasicResourcePool@5e10e82c -- an attempt to checkout a resource was interrupted, and the pool is still live: some other thread must have interrupted the Thread attempting checkout!
java.lang.InterruptedException: null
	at java.lang.Object.wait(Native Method)
	at com.mchange.v2.resourcepool.BasicResourcePool.awaitAvailable(BasicResourcePool.java:1503)
	at com.mchange.v2.resourcepool.BasicResourcePool.prelimCheckoutResource(BasicResourcePool.java:644)
	at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:554)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutAndMarkConnectionInUse(C3P0PooledConnectionPool.java:758)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:685)
	at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(AbstractPoolBackedDataSource.java:140)
	at slick.jdbc.DataSourceJdbcDataSource.createConnection(JdbcDataSource.scala:71)
	at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:494)
	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
	at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:250)
	at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:249)
	at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
	at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:275)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Attached the logs for reference. I have followed the steps mentioned in the README.md for docker running.

Can someone please help

**Comment by Nitu-coder** [comment]
> My echange api build is successfull
> but when i try to run the docker image using docker run image_name:tag
> I get the following error after it starts running and then stops
> 
> 2020-04-01 13:10:38,122 [ExchangeExecutor-1] INFO c.m.v.c.i.AbstractPoolBackedDataSource - Initializing c3p0 pool... com.mchange.v2.c3p0.ComboPooledDataSource [ acquireIncrement -> 1, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, contextClassLoaderSource -> caller, dataSourceName -> 1bqq1hfa9ey1j151oiv08|31e75d13, debugUnreturnedConnectionStackTraces -> false, description -> null, driverClass -> org.postgresql.Driver, extensions -> {}, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, forceSynchronousCheckins -> false, forceUseNamedDriverClass -> false, identityToken -> 1bqq1hfa9ey1j151oiv08|31e75d13, idleConnectionTestPeriod -> 0, initialPoolSize -> 3, jdbcUrl -> , maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 0, maxIdleTimeExcessConnections -> 0, maxPoolSize -> 50, maxStatements -> 0, maxStatementsPerConnection -> 0, minPoolSize -> 1, numHelperThreads -> 3, preferredTestQuery -> null, privilegeSpawnedThreads -> false, properties -> {user=******, password=******}, propertyCycle -> 0, statementCacheNumDeferredCloseThreads -> 0, testConnectionOnCheckin -> false, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, userOverrides -> {}, usesTraditionalReflectiveProxies -> false ]
> 2020-04-01 13:11:08,224 [C3P0PooledConnectionPoolManager[identityToken->1bqq1hfa9ey1j151oiv08|31e75d13]-HelperThread-#0] WARN c.m.v.resourcepool.BasicResourcePool - com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask@793a74da -- Acquisition Attempt Failed!!! Clearing pending acquires. While trying to acquire a needed new resource, we failed to succeed more than the maximum number of allowed acquisition attempts (30). Last acquisition attempt exception:
> java.sql.SQLException: No suitable driver
> at java.sql.DriverManager.getDriver(DriverManager.java:315)
> at com.mchange.v2.c3p0.DriverManagerDataSource.driver(DriverManagerDataSource.java:285)
> at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:175)
> at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220)
> at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206)
> at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:203)
> at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1176)
> at com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1163)
> at com.mchange.v2.resourcepool.BasicResourcePool.access$700(BasicResourcePool.java:44)
> at com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1908)
> at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)
> 2020-04-01 13:11:08,224 [C3P0PooledConnectionPoolManager[identityToken->1bqq1hfa9ey1j151oiv08|31e75d13]-HelperThread-#2] WARN c.m.v.resourcepool.BasicResourcePool - com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask@184392bf -- Acquisition Attempt Failed!!! Clearing pending acquires. While trying to acquire a needed new resource, we failed to succeed more than the maximum number of allowed acquisition attempts (30). Last acquisition attempt exception:
> java.sql.SQLException: No suitable driver
> at java.sql.DriverManager.getDriver(DriverManager.java:315)
> at com.mchange.v2.c3p0.DriverManagerDataSource.driver(DriverManagerDataSource.java:285)
> at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:175)
> at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220)
> at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206)
> at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:203)
> at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1176)
> at com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1163)
> at com.mchange.v2.resourcepool.BasicResourcePool.access$700(BasicResourcePool.java:44)
> at com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1908)
> at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)
> 2020-04-01 13:11:08,225 [C3P0PooledConnectionPoolManager[identityToken->1bqq1hfa9ey1j151oiv08|31e75d13]-HelperThread-#0] WARN c.m.v.resourcepool.BasicResourcePool - Having failed to acquire a resource, com.mchange.v2.resourcepool.BasicResourcePool@5e10e82c is interrupting all Threads waiting on a resource to check out. Will try again in response to new client requests.
> 2020-04-01 13:11:08,227 [C3P0PooledConnectionPoolManager[identityToken->1bqq1hfa9ey1j151oiv08|31e75d13]-HelperThread-#2] WARN c.m.v.resourcepool.BasicResourcePool - Having failed to acquire a resource, com.mchange.v2.resourcepool.BasicResourcePool@5e10e82c is interrupting all Threads waiting on a resource to check out. Will try again in response to new client requests.
> [ERROR] [04/01/2020 13:11:08.259] [main] [ExchApi(akka://actors)] Error: while upgrading the DB, the DB threw exception: Connections could not be acquired from the underlying database!
> Exception in thread "main" java.lang.IllegalStateException: cannot create children while terminating or terminated
> at akka.actor.dungeon.Children.makeChild(Children.scala:287)
> at akka.actor.dungeon.Children.attachChild(Children.scala:49)
> at akka.actor.dungeon.Children.attachChild$(Children.scala:48)
> at akka.actor.ActorCell.attachChild(ActorCell.scala:447)
> at akka.actor.ActorSystemImpl.actorOf(ActorSystem.scala:783)
> at com.horizon.exchangeapi.ExchangeApiApp$.delayedEndpoint$com$horizon$exchangeapi$ExchangeApiApp$1(ExchangeApiApp.scala:250)
> at com.horizon.exchangeapi.ExchangeApiApp$delayedInit$body.apply(ExchangeApiApp.scala:59)
> at scala.Function0.apply$mcV$sp(Function0.scala:39)
> at scala.Function0.apply$mcV$sp$(Function0.scala:39)
> at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
> at scala.App.$anonfun$main$1$adapted(App.scala:80)
> at scala.collection.immutable.List.foreach(List.scala:392)
> at scala.App.main(App.scala:80)
> at scala.App.main$(App.scala:78)
> at com.horizon.exchangeapi.ExchangeApiApp$.main(ExchangeApiApp.scala:59)
> at com.horizon.exchangeapi.ExchangeApiApp.main(ExchangeApiApp.scala)
> 2020-04-01 13:11:08,303 [ExchangeExecutor-2] WARN c.m.v.resourcepool.BasicResourcePool - com.mchange.v2.resourcepool.BasicResourcePool@5e10e82c -- an attempt to checkout a resource was interrupted, and the pool is still live: some other thread must have interrupted the Thread attempting checkout!
> java.lang.InterruptedException: null
> at java.lang.Object.wait(Native Method)
> at com.mchange.v2.resourcepool.BasicResourcePool.awaitAvailable(BasicResourcePool.java:1503)
> at com.mchange.v2.resourcepool.BasicResourcePool.prelimCheckoutResource(BasicResourcePool.java:644)
> at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:554)
> at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutAndMarkConnectionInUse(C3P0PooledConnectionPool.java:758)
> at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:685)
> at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(AbstractPoolBackedDataSource.java:140)
> at slick.jdbc.DataSourceJdbcDataSource.createConnection(JdbcDataSource.scala:71)
> at slick.jdbc.JdbcBackend$BaseSession.(JdbcBackend.scala:494)
> at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
> at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
> at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:250)
> at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:249)
> at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
> at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:275)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> at java.lang.Thread.run(Thread.java:748)
> 
> Attached the logs for reference. I have followed the steps mentioned in the README.md for docker running.
> 
> Can someone please help me

**Comment by Nitu-coder** [comment]
databse url issue. its resolved

**Comment by codejaeger** [comment]
Hi @Nitu-coder, could you mention what you did to solve the above? I know this is an old issue but if you could remember what worked for you I would be very grateful. Thanks!
